# Generated by Django 2.0.6 on 2020-03-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TAdmin',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(blank=True, max_length=500, null=True)),
                ('t_pwd', models.CharField(blank=True, max_length=500, null=True)),
                ('t_flag', models.CharField(blank=True, max_length=500, null=True)),
                ('column_5', models.CharField(blank=True, db_column='Column_5', max_length=10, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=10, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TArtide',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('t_title', models.CharField(blank=True, max_length=500, null=True)),
                ('t_time', models.CharField(blank=True, max_length=500, null=True)),
                ('t_content', models.CharField(blank=True, max_length=500, null=True)),
                ('t_category', models.CharField(blank=True, max_length=500, null=True)),
                ('t_tid', models.CharField(blank=True, max_length=500, null=True)),
                ('t_contentpic', models.CharField(blank=True, max_length=500, null=True)),
                ('column_9', models.CharField(blank=True, db_column='Column_9', max_length=10, null=True)),
                ('column_10', models.CharField(blank=True, db_column='Column_10', max_length=10, null=True)),
                ('column_11', models.CharField(blank=True, db_column='Column_11', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_artide',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TSlideshow',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_url', models.ImageField(upload_to='img')),
                ('t_title', models.CharField(blank=True, max_length=500, null=True)),
                ('t_flag', models.CharField(blank=True, max_length=500, null=True)),
                ('t_createtime', models.CharField(blank=True, max_length=500, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=10, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_slideshow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TTeacher',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('t_name', models.CharField(blank=True, max_length=500, null=True)),
                ('t_flag', models.CharField(blank=True, max_length=500, null=True)),
                ('column_5', models.CharField(blank=True, db_column='Column_5', max_length=10, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=10, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_teacher',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(blank=True, max_length=500, null=True)),
                ('t_tel', models.CharField(blank=True, max_length=500, null=True)),
                ('t_pwd', models.CharField(blank=True, max_length=500, null=True)),
                ('t_salt', models.CharField(blank=True, max_length=500, null=True)),
                ('t_add', models.CharField(blank=True, max_length=500, null=True)),
                ('t_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('t_nota', models.CharField(blank=True, max_length=500, null=True)),
                ('t_sex', models.CharField(blank=True, max_length=500, null=True)),
                ('t_flag', models.CharField(blank=True, max_length=500, null=True)),
                ('column_11', models.CharField(blank=True, db_column='Column_11', max_length=10, null=True)),
                ('column_12', models.CharField(blank=True, db_column='Column_12', max_length=10, null=True)),
                ('column_13', models.CharField(blank=True, db_column='Column_13', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TVoice',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_title', models.CharField(blank=True, max_length=500, null=True)),
                ('t_url', models.CharField(blank=True, max_length=500, null=True)),
                ('t_duration', models.CharField(blank=True, max_length=500, null=True)),
                ('t_vlid', models.CharField(blank=True, max_length=500, null=True)),
                ('t_size', models.CharField(blank=True, max_length=500, null=True)),
                ('column_9', models.CharField(blank=True, db_column='Column_9', max_length=10, null=True)),
                ('column_10', models.CharField(blank=True, db_column='Column_10', max_length=10, null=True)),
                ('column_11', models.CharField(blank=True, db_column='Column_11', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_voice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TVoicelist',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_pic', models.CharField(blank=True, max_length=500, null=True)),
                ('t_title', models.CharField(blank=True, max_length=500, null=True)),
                ('t_grade', models.CharField(blank=True, max_length=500, null=True)),
                ('t_time', models.CharField(blank=True, max_length=500, null=True)),
                ('t_author', models.CharField(blank=True, max_length=500, null=True)),
                ('t_announcer', models.CharField(blank=True, max_length=500, null=True)),
                ('t_count', models.CharField(blank=True, max_length=500, null=True)),
                ('t_content', models.CharField(blank=True, max_length=500, null=True)),
                ('column_10', models.CharField(blank=True, db_column='Column_10', max_length=10, null=True)),
                ('column_11', models.CharField(blank=True, db_column='Column_11', max_length=10, null=True)),
                ('column_12', models.CharField(blank=True, db_column='Column_12', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_voicelist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TWork',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_title', models.CharField(blank=True, max_length=500, null=True)),
                ('t_time', models.CharField(blank=True, max_length=500, null=True)),
                ('t_count', models.CharField(blank=True, max_length=500, null=True)),
                ('t_wlid', models.CharField(blank=True, max_length=500, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=10, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=10, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_work',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TWorklist',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_title', models.CharField(blank=True, max_length=500, null=True)),
                ('t_category', models.CharField(blank=True, max_length=500, null=True)),
                ('t_uid', models.CharField(blank=True, max_length=500, null=True)),
                ('column_6', models.CharField(blank=True, db_column='Column_6', max_length=10, null=True)),
                ('column_7', models.CharField(blank=True, db_column='Column_7', max_length=10, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=10, null=True)),
            ],
            options={
                'db_table': 't_worklist',
                'managed': True,
            },
        ),
    ]
